//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapNhatGia
    {
        public int IdCapNhat { get; set; }
        public Nullable<int> IdTU { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    }
}
