//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int IdCTPN { get; set; }
        public Nullable<int> IdPN { get; set; }
        public Nullable<int> IdNL { get; set; }
        public Nullable<int> IdNhaCC { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    }
}
