//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietCart
    {
        public int IdCTCart { get; set; }
        public int IdCart { get; set; }
        public int IdTU { get; set; }
        public string Size { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    }
}
