//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemTra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongThuc
    {
        public int IdNLTU { get; set; }
        public int IdTU { get; set; }
        public Nullable<int> IdNL { get; set; }
        public int SoLuong { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> IdSize { get; set; }
    }
}
